name: Auto Tag on Semantic Version PR

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract semantic version from PR title
        id: get_version
        run: |
          VERSION=$(echo "${{ github.event.pull_request.title }}" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          if [ -n "$VERSION" ]; then
            echo "version=$VERSION" >> $GITHUB_ENV
            echo "Semantic version found: $VERSION"
          else
            echo "No semantic version found, skipping tag creation."
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          git tag ${{ env.version }}
          git push origin ${{ env.version }}
