name: Auto Tag on Semantic Version Commit

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract semantic version from commit message
        id: get_version
        run: |
          VERSION=$(git log -1 --pretty=%B | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          if [ -n "$VERSION" ]; then
            echo "version=$VERSION" >> $GITHUB_ENV
            echo "Semantic version found: $VERSION"
          else
            echo "No semantic version found, skipping tag creation."
            exit 0
          fi

      - name: Create and push tag
        if: env.version != ''
        run: |
          git tag ${{ env.version }}
          git push origin ${{ env.version }}
